# Generated by Django 4.1.1 on 2023-01-29 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('actual', models.BooleanField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.CharField(max_length=100, verbose_name='Make')),
                ('model', models.CharField(max_length=100)),
                ('generation', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('hash_rate', models.FloatField()),
                ('power', models.FloatField()),
                ('power_variance', models.FloatField()),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.price')),
            ],
            options={
                'abstract': False,
                'unique_together': {('make', 'model', 'generation')},
            },
        ),
    ]
