# Generated by Django 4.1.1 on 2023-01-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rig',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='rig',
            name='generation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rig',
            unique_together={('make', 'model', 'generation', 'price')},
        ),
    ]
