# Generated by Django 4.1.1 on 2023-01-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_price_date_alter_rig_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='actual',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='rig',
            unique_together={('make', 'model', 'generation')},
        ),
    ]
