# Generated by Django 4.1.1 on 2023-01-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_price_actual_alter_rig_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
