# Generated by Django 4.1.1 on 2023-01-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_price_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rig',
            old_name='power_variance',
            new_name='buffer',
        ),
    ]
