# Generated by Django 4.1.1 on 2023-01-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_power_variance_rig_buffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='rig',
            name='new_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
