# Generated by Django 4.1.1 on 2023-01-29 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rig_new_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rig',
            name='price',
        ),
    ]
