# Generated by Django 4.1.1 on 2023-01-29 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_rig_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rig',
            old_name='new_price',
            new_name='price',
        ),
    ]
