# Generated by Django 4.1.1 on 2023-01-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_delete_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rig',
            unique_together=set(),
        ),
    ]
