# Generated by Django 4.1.1 on 2023-02-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_cooling_electrical_heatrejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooling',
            name='power',
            field=models.FloatField(default=0, verbose_name='Power'),
        ),
        migrations.AddField(
            model_name='electrical',
            name='power',
            field=models.FloatField(default=0, verbose_name='Power'),
        ),
        migrations.AddField(
            model_name='heatrejection',
            name='power',
            field=models.FloatField(default=0, verbose_name='Power'),
        ),
    ]
