# Generated by Django 4.1.1 on 2023-02-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_cooling_power_electrical_power_heatrejection_power'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
            ],
        ),
    ]
