# Generated by Django 4.1.1 on 2023-02-09 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rejectioncurve'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatrejection',
            name='curve',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.rejectioncurve'),
        ),
    ]
