# Generated by Django 4.1.1 on 2023-02-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_heatrejection_curve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooling',
            name='power',
            field=models.FloatField(default=None, verbose_name='Power'),
        ),
        migrations.AlterField(
            model_name='electrical',
            name='power',
            field=models.FloatField(default=None, verbose_name='Power'),
        ),
        migrations.AlterField(
            model_name='heatrejection',
            name='power',
            field=models.FloatField(default=None, verbose_name='Power'),
        ),
    ]
