# Generated by Django 4.1.1 on 2023-02-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_cooling_power_alter_electrical_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooling',
            name='number_of_rigs',
            field=models.FloatField(default=None, null=True, verbose_name='Number of rigs'),
        ),
    ]
