# Generated by Django 4.1.1 on 2023-03-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_cooling_number_of_rigs'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatrejection',
            name='design_dry_bulb',
            field=models.FloatField(default=95, null=True, verbose_name='Design Dry Bulb Temperature'),
        ),
    ]
