# Generated by Django 4.1.1 on 2023-03-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_rejectioncurve_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatrejection',
            name='curve',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.rejectioncurve'),
        ),
        migrations.AlterField(
            model_name='rejectioncurve',
            name='a',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rejectioncurve',
            name='b',
            field=models.FloatField(null=True),
        ),
    ]
