# Generated by Django 4.1.1 on 2023-03-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_heatrejection_curve_alter_rejectioncurve_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooling',
            name='power',
        ),
        migrations.RemoveField(
            model_name='electrical',
            name='power',
        ),
        migrations.RemoveField(
            model_name='heatrejection',
            name='power',
        ),
        migrations.AddField(
            model_name='cooling',
            name='capacity',
            field=models.FloatField(default=None, verbose_name='Power Capacity'),
        ),
        migrations.AddField(
            model_name='electrical',
            name='capacity',
            field=models.FloatField(default=None, verbose_name='Power Capacity'),
        ),
        migrations.AddField(
            model_name='heatrejection',
            name='capacity',
            field=models.FloatField(default=None, verbose_name='Power Capacity'),
        ),
    ]
