# Generated by Django 4.1.1 on 2023-03-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_cooling_power_remove_electrical_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooling',
            name='capacity',
            field=models.FloatField(default=None, null=True, verbose_name='Power Capacity'),
        ),
        migrations.AlterField(
            model_name='electrical',
            name='capacity',
            field=models.FloatField(default=None, null=True, verbose_name='Power Capacity'),
        ),
        migrations.AlterField(
            model_name='heatrejection',
            name='capacity',
            field=models.FloatField(default=None, null=True, verbose_name='Power Capacity'),
        ),
    ]
