# Generated by Django 4.1.1 on 2023-03-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_heatrejection_curve'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectioncurve',
            name='p',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rejectioncurve',
            name='r',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rejectioncurve',
            name='serr',
            field=models.FloatField(null=True),
        ),
    ]
