# Generated by Django 4.1.1 on 2023-03-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_rejectioncurve_p_rejectioncurve_r_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStations',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('elevation', models.FloatField(verbose_name='Elevation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
