# Generated by Django 4.1.1 on 2023-03-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_weatherstations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeatherStations',
            new_name='WeatherStation',
        ),
    ]
