# Generated by Django 4.1.1 on 2023-03-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_rename_weatherstations_weatherstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherstation',
            name='elevation',
            field=models.FloatField(verbose_name='Elevation (in feet))'),
        ),
    ]
