# Generated by Django 4.1.1 on 2023-03-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_weatherstation_elevation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('units', models.CharField(default='IP', max_length=100, null=True)),
                ('period', models.CharField(max_length=100, null=True)),
                ('variable', models.CharField(max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.weatherstation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
