# Generated by Django 4.1.1 on 2023-04-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_weatherdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rig',
            name='make',
            field=models.CharField(max_length=100, null=True, verbose_name='Make'),
        ),
        migrations.AlterField(
            model_name='rig',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rig',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
