# Generated by Django 4.1.1 on 2023-02-09 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_cooling_power_alter_electrical_power_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity', models.FloatField(verbose_name='Capacity')),
                ('target_ambient_temp', models.FloatField(default=95, verbose_name='Target Ambient Temperature')),
                ('target_overclocking', models.FloatField(default=1, verbose_name='Target Overclock Factor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rigforproject',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rig', to='products.rig'),
        ),
        migrations.AddField(
            model_name='infraforproject',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure', to='projects.project'),
        ),
    ]
