# Generated by Django 4.1.1 on 2023-02-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_rigforproject_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infraforproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='rigforproject',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='energy_price',
            field=models.FloatField(default=0, verbose_name='Energy Price'),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='New Project', max_length=100, verbose_name='Name'),
        ),
    ]
