# Generated by Django 4.1.1 on 2023-02-09 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0016_alter_cooling_power_alter_electrical_power_and_more'),
        ('projects', '0004_remove_infraforproject_infra_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='New Project', max_length=100, verbose_name='Name')),
                ('capacity', models.FloatField(verbose_name='Capacity')),
                ('target_ambient_temp', models.FloatField(default=95, verbose_name='Target Ambient Temperature')),
                ('target_overclocking', models.FloatField(default=1, verbose_name='Target Overclock Factor')),
                ('energy_price', models.FloatField(default=0, verbose_name='Energy Price')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RigForProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('rig', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.rig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfraForProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('infra_object_id', models.IntegerField()),
                ('infra_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
