# Generated by Django 4.1.1 on 2023-02-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_rigforproject_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='infraforproject',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='rigforproject',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Quantity'),
        ),
    ]
