# Generated by Django 4.1.1 on 2023-02-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_infraforproject_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('projects', models.ManyToManyField(related_name='projects', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
