# Generated by Django 4.1.1 on 2023-02-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='projects',
            field=models.ManyToManyField(to='projects.project'),
        ),
    ]
