# Generated by Django 4.1.1 on 2023-02-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_infraforproject_amortization_project_pool_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tax_rate',
            field=models.FloatField(default=0, verbose_name='Tax Rate'),
        ),
    ]
