# Generated by Django 4.1.1 on 2023-02-20 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_opex_project_property_taxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freq', models.CharField(blank=True, max_length=1, null=True, verbose_name='Frequency')),
                ('stat', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
