# Generated by Django 4.1.1 on 2023-02-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_projectstatement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectstatement',
            old_name='stat',
            new_name='istat',
        ),
        migrations.RemoveField(
            model_name='projectstatement',
            name='freq',
        ),
        migrations.AddField(
            model_name='projectstatement',
            name='profitability',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='projectstatement',
            name='roi',
            field=models.JSONField(default=dict),
        ),
    ]
