# Generated by Django 4.1.1 on 2023-02-20 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0011_environment'),
        ('projects', '0021_rename_stat_projectstatement_istat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstatement',
            name='project',
        ),
        migrations.AddField(
            model_name='projectstatement',
            name='sim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='projects.project'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='environment.environment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
