# Generated by Django 4.1.1 on 2023-02-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_remove_projectstatement_project_projectstatement_sim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatement',
            name='env',
            field=models.JSONField(default=dict),
        ),
    ]
