# Generated by Django 4.1.1 on 2023-02-20 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_projectstatement_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatement',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.projectsimulation'),
        ),
    ]
