# Generated by Django 4.1.1 on 2023-02-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_remove_projectstatement_env_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatement',
            name='env',
            field=models.JSONField(default=dict),
        ),
    ]
