# Generated by Django 4.1.1 on 2023-02-28 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_projectstatement_env'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstatement',
            name='profitability',
        ),
        migrations.AlterField(
            model_name='projectstatement',
            name='frequency',
            field=models.CharField(choices=[('10T', '10 Minutes'), ('D', 'Daily'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('A', 'Annually')], max_length=10, verbose_name='Frequency'),
        ),
        migrations.CreateModel(
            name='ProjectStatementSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.JSONField(default=dict)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.projectsimulation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
