# Generated by Django 4.1.1 on 2023-03-27 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_weatherdata'),
        ('projects', '0028_remove_projectstatement_profitability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ambient_temp_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='products.weatherstation'),
        ),
    ]
