# Generated by Django 4.1.1 on 2023-04-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_project_ambient_temp_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='target_ambient_temp',
            field=models.JSONField(default=dict, verbose_name='Target Ambient Temperature'),
        ),
    ]
