# Generated by Django 4.1.1 on 2023-04-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_alter_project_target_ambient_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatement',
            name='roi',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
