# Generated by Django 4.1.1 on 2023-04-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_alter_projectstatement_roi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatement',
            name='roi',
            field=models.JSONField(default=dict),
        ),
    ]
