# Generated by Django 4.1.1 on 2023-04-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_infraforproject_price_rigforproject_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatement',
            name='roi',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
