# Generated by Django 4.1.1 on 2023-04-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_alter_projectstatement_roi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatement',
            name='frequency',
            field=models.CharField(choices=[('10T', '10 Minutes'), ('H', 'Hourly'), ('D', 'Daily'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('A', 'Annually')], max_length=10, verbose_name='Frequency'),
        ),
    ]
