# Generated by Django 4.1.1 on 2023-04-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0011_environment'),
        ('projects', '0036_alter_projectstatement_frequency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectsimulation',
            unique_together={('environment', 'project')},
        ),
    ]
