# Generated by Django 4.1.1 on 2023-04-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_alter_projectsimulation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='capacity',
            field=models.FloatField(default=0, verbose_name='Capacity'),
        ),
    ]
