# Generated by Django 4.1.1 on 2023-04-24 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_cooling_name_alter_electrical_name_and_more'),
        ('projects', '0038_alter_project_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ambient_temp_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='products.weatherstation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='energy_price',
            field=models.FloatField(default=0, verbose_name='Energy Price'),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_ambient_temp',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Target Ambient Temperature'),
        ),
    ]
