# Generated by Django 4.1.1 on 2023-01-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_epoch', models.PositiveSmallIntegerField()),
                ('json', models.JSONField()),
            ],
            options={
                'unique_together': {('start_date', 'end_epoch')},
            },
        ),
    ]
