# Generated by Django 4.1.1 on 2023-01-31 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockschedule',
            old_name='end_epoch',
            new_name='last_epoch',
        ),
        migrations.AlterUniqueTogether(
            name='blockschedule',
            unique_together={('start_date', 'last_epoch')},
        ),
    ]
