# Generated by Django 4.1.1 on 2023-02-02 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_bitcoinprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitcoinPrice',
        ),
    ]
