# Generated by Django 4.1.1 on 2023-02-02 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0004_delete_bitcoinprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(choices=[('constant', 'Constant'), ('cgr', 'CGR'), ('gbm', 'GBM')], max_length=20)),
                ('initial_value', models.FloatField()),
                ('mean', models.FloatField(null=True)),
                ('volatility', models.FloatField(null=True)),
                ('json', models.JSONField()),
                ('blocks', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='environment.blockschedule')),
            ],
            options={
                'abstract': False,
                'unique_together': {('initial_value', 'mean', 'volatility', 'model', 'blocks')},
            },
        ),
    ]
