# Generated by Django 4.1.1 on 2023-02-02 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0005_bitcoinprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitcoinprice',
            old_name='model',
            new_name='forecast_model',
        ),
        migrations.AlterUniqueTogether(
            name='bitcoinprice',
            unique_together={('initial_value', 'mean', 'volatility', 'forecast_model', 'blocks')},
        ),
    ]
