# Generated by Django 4.1.1 on 2023-02-02 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0006_rename_model_bitcoinprice_forecast_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitcoinprice',
            old_name='forecast_model',
            new_name='model',
        ),
        migrations.AlterUniqueTogether(
            name='bitcoinprice',
            unique_together={('initial_value', 'mean', 'volatility', 'model', 'blocks')},
        ),
    ]
