# Generated by Django 4.1.1 on 2023-02-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0007_rename_forecast_model_bitcoinprice_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitcoinprice',
            old_name='initial_value',
            new_name='initial',
        ),
        migrations.AlterUniqueTogether(
            name='bitcoinprice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bitcoinprice',
            name='model',
            field=models.CharField(choices=[('Constant', 'Constant'), ('CGR', 'CGR'), ('GBM', 'GBM')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='bitcoinprice',
            unique_together={('initial', 'mean', 'volatility', 'model', 'blocks')},
        ),
        migrations.AlterUniqueTogether(
            name='blockschedule',
            unique_together={('id', 'start_date', 'last_epoch')},
        ),
    ]
