# Generated by Django 4.1.1 on 2023-02-05 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0008_rename_initial_value_bitcoinprice_initial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(choices=[('Constant', 'Constant'), ('CGR', 'CGR'), ('GBM', 'GBM')], max_length=20)),
                ('initial', models.FloatField()),
                ('mean', models.FloatField(null=True)),
                ('volatility', models.FloatField(null=True)),
                ('json', models.JSONField()),
                ('blocks', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='environment.blockschedule')),
            ],
            options={
                'abstract': False,
                'unique_together': {('initial', 'mean', 'volatility', 'model', 'blocks')},
            },
        ),
        migrations.CreateModel(
            name='HashRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(choices=[('Constant', 'Constant'), ('CGR', 'CGR'), ('GBM', 'GBM')], max_length=20)),
                ('initial', models.FloatField()),
                ('mean', models.FloatField(null=True)),
                ('volatility', models.FloatField(null=True)),
                ('json', models.JSONField()),
                ('blocks', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='environment.blockschedule')),
            ],
            options={
                'abstract': False,
                'unique_together': {('initial', 'mean', 'volatility', 'model', 'blocks')},
            },
        ),
    ]
