# Generated by Django 4.1.1 on 2023-02-10 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0009_transactionfees_hashrate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bitcoinprice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='hashrate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='transactionfees',
            unique_together=set(),
        ),
    ]
