# Generated by Django 4.1.1 on 2023-02-11 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0010_alter_bitcoinprice_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('bitcoin_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='environment.bitcoinprice')),
                ('block_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='environment.blockschedule')),
                ('hash_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='environment.hashrate')),
                ('transaction_fees', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='environment.transactionfees')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
